name: 'Deploy SQL Failover Group'
run-name: '${{github.actor}} - Deployingto_${{inputs.subscription}}_${{inputs.environment}}'
on:
    workflow_dispatch:
      inputs:
        requesttype:
          type: choice
          required: true
          description: Request Type
          options:
              - Create
              - Remove
          default: "Create"
        primary_server_id:
          type: string
          required: true
          description: Primary SQL Server Resource ID
        secondary_server_id:
          type: string
          required: true
          description: Secondary SQL Server Resource ID
        database_ids:
          type: string
          required: true
          description: Database IDs (comma-separated list)
        subscription:
          type: string
          required: true
          description: Please enter your subcription Name
        location_pair:
          type: choice
          description: Select Primary-Secondary Location Pair
          required: true
          options:
            - '["eastus2","centralus"]'
            - '["centralus","eastus2"]'
        environment:
          type: choice
          description: choose the environment
          options:
             - dev
             - qa 
             - UAT
             - Prod
        purpose:
          type: string
          description: Failover Group purpose
          required: true

jobs:
  sql-failover_create:
    if: (github.event.inputs.requestType == 'Create')
    name: 'Deploying - MSSQL Failover Group'
    uses: ./.github/workflows/CreateMSSQLFailover.yml
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      primary_server_id: '${{inputs.primary_server_id}}'
      secondary_server_id: '${{inputs.secondary_server_id}}'
      database_ids: '${{inputs.database_ids}}'
      location: '${{ fromJson(inputs.location_pair)[0] }}'
      secondary_location: '${{ fromJson(inputs.location_pair)[1] }}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'

  sql-failover_remove:
    if: (github.event.inputs.requestType == 'Remove')
    name: 'Removing - MSSQL Failover Group'
    uses: ./.github/workflows/CreateMSSQLFailover.yml
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      primary_server_id: '${{inputs.primary_server_id}}'
      secondary_server_id: '${{inputs.secondary_server_id}}'
      database_ids: '${{inputs.database_ids}}'
      location: '${{ fromJson(inputs.location_pair)[0] }}'
      secondary_location: '${{ fromJson(inputs.location_pair)[1] }}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      destroy: true 